version: '3.8'

services:
  img:
    image: devsunil27/jobtracker-backend
    container_name: jobtracker-backend
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/data # Add volume for persistent backend data
    networks:
      - mern

  imgg:
    image: devsunil27/jobtracker-frontend
    container_name: jobtracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - img # Ensure frontend starts after backend
    networks:
      - mern

networks:
  mern:
    driver: bridge

volumes:
  backend_data: # Volume for backend
